title: "2083"
author: "Brendan McCormick"
description: "A showcase for contemporary art pieces located somewhere between art and design. Informed by a simple impulse or thought and influenced by process and circumstance, the work attempts to present the qualities inherent in an object or material."
baseurl: "/"
url: "http://twozeroeightthree.com"
lang: en

plugins: [jekyll-sitemap, jekyll-seo-tag]

permalink: /:title/

exclude: [ref.pdf, size-ref.png, README.md, notes.md, CNAME, compile.sh, _posts/2000-01-01-template.html]
